### ISSUE TITLE
preproc.py

### ISSUE THREAD

**Issue by attaullah** [alexandrebarachant/bci-challenge-ner-2015#1]
On line number 57 :    

 idxFeedBack = find(Trigger)

above line has error while runing saying: 

NameError: name 'find' is not defined

**Comment by alexandrebarachant** [comment]
find is supposed to comes from pylab.

Which version of python did you use ?

As an alternative, you can replace this line by : 

```idxFeedBack = np.where(Trigger==1)[0]```

let me know if it works, i will commit the change.

**Comment by attaullah** [comment]
OK dear great. alternate solution works flawlessly.
